set -x
time ~/ccsergez/fillit ~/fillit_tests/9L.fillit
time ~/ccsergez/fillit ~/fillit_tests/bad1.fillit
time ~/ccsergez/fillit ~/fillit_tests/bad2.fillit
time ~/ccsergez/fillit ~/fillit_tests/bad3.fillit
time ~/ccsergez/fillit ~/fillit_tests/bad4.fillit
time ~/ccsergez/fillit ~/fillit_tests/bad5.fillit
time ~/ccsergez/fillit ~/fillit_tests/bad6.fillit
time ~/ccsergez/fillit ~/fillit_tests/bad7.fillit
time ~/ccsergez/fillit ~/fillit_tests/bad8.fillit
time ~/ccsergez/fillit ~/fillit_tests/bad9.fillit
time ~/ccsergez/fillit ~/fillit_tests/badsample.fillit
time ~/ccsergez/fillit ~/fillit_tests/exforum.fillit
time ~/ccsergez/fillit ~/fillit_tests/exv3.fillit
time ~/ccsergez/fillit ~/fillit_tests/exv4.fillit
time ~/ccsergez/fillit ~/fillit_tests/exv5.fillit
time ~/ccsergez/fillit ~/fillit_tests/fofo.fillit
time ~/ccsergez/fillit ~/fillit_tests/goodsample.fillit
time ~/ccsergez/fillit ~/fillit_tests/long.fillit
time ~/ccsergez/fillit ~/fillit_tests/omg10.fillit
time ~/ccsergez/fillit ~/fillit_tests/omg11.fillit
time ~/ccsergez/fillit ~/fillit_tests/omg26.fillit
time ~/ccsergez/fillit ~/fillit_tests/omgsimple.fillit
time ~/ccsergez/fillit ~/fillit_tests/perfect.fillit
time ~/ccsergez/fillit ~/fillit_tests/sample.fillit
time ~/ccsergez/fillit ~/fillit_tests/sample2.fillit
time ~/ccsergez/fillit ~/fillit_tests/samplestaff
time ~/ccsergez/fillit ~/fillit_tests/staff.fillit
time ~/ccsergez/fillit ~/fillit_tests/test.fillit
time ~/ccsergez/fillit ~/fillit_tests/test3
time ~/ccsergez/fillit ~/fillit_tests/tocheck.fillit
